### ISSUE TITLE
question about the hazy image generation

### ISSUE THREAD

**Issue by zyhrainbow** [Xiangtaokong/MiOIR#2]
How to get the depth you've used. Thanks~

**Comment by Xiangtaokong** [comment]
We follow the commonly uesd Dehaze Dataset -- RESIDE. Specifically, the haze generation code is derived from "Learning Depth from Single Monocular Images Using Deep Convolutional Neural Fields" ([github](https://github.com/comeonyang/Depth-Estimation-DCNF)). 

The citation number of this work in RESIDE is [38]. I will update this work to the reference of MiOIR to make it clearer.
