### ISSUE TITLE
Request for Single-Task Pre-Trained Weights

### ISSUE THREAD

**Issue by Aitical** [Xiangtaokong/MiOIR#4]
<img width="821" alt="image" src="https://github.com/Xiangtaokong/MiOIR/assets/23092190/363c02e1-5663-410f-b6f2-7b3ff11b20bb">

It is really a wonderful work! 

I noticed that the results in Table A.1 of the supplementary materials include the results of 7 single tasks. I am wondering if you could share the pre-training weights of the single-task model.

Considering there is a new benchmark on DF2K dataset with multiple degradation tasks, it would be of great help to my research and enable me to further analyze and study with these pre-trained weights. 

If it is possible, I would be very grateful if you could provide the pre-training weights.

**Comment by Xiangtaokong** [comment]
Thank you for your attention.
Sure, I can release these models. But I am busy with eccv recently, I will update the model as soon as possible after the eccv deadline.

**Comment by Aitical** [comment]
Thanks for your quick reply 👍 👍,  I am looking forward to your sharing.

Best wishes for your next work.

**Comment by Xiangtaokong** [comment]
I have uploaded the models in /MIOIR/pretrained_model/single_baseline. Note, they were only trained 20w-50w iterations, which may not be very sufficient.

**Comment by Aitical** [comment]
Thank you again for your nice sharing!! 👍 👍
