### ISSUE TITLE
about the restormer-ep arch

### ISSUE THREAD

**Issue by alexhe101** [Xiangtaokong/MiOIR#5]
According to the paper, it is stated that the prompt features would be injected solely into the encoder part of the U-Net-like structure. However, upon inspecting the restormer_ep code, it is observed that the prompt features are being injected into the decoder part instead. Why is that? Does injecting into the decoder part bring higher performance?

**Comment by Xiangtaokong** [comment]
Thanks for your careful reading. The code should prevail, which the prompt is added in decoder. I will revise the paper.

According to our observation, for U-like structures, the key is to provide different prompt features for each U scale. Adding to an encoder or decoder or both has little effect.

**Comment by alexhe101** [comment]
Thank you for your reply, really helpful!
